# 1. Load iris dataset from Scikitlearn using load_iris(). Assign the dataset to x and the target values to y.

In [1]:
!pip install scikit-learn

In [2]:
import sklearn as sklearn

In [3]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

# 2. Print the dataset keys using iris_dataset.keys()

In [4]:
print(iris_dataset.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


# 3. Print the names of the categories in the target file

In [5]:
print(iris_dataset['target_names'])

['setosa' 'versicolor' 'virginica']


# 4. Print the feature names in the Iris dataset.

In [6]:
print(iris_dataset['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


# 5. Print the type of the iris dataset.

In [7]:
print(type(iris_dataset['data']))

<class 'numpy.ndarray'>


# 6. Print the shape of the iris dataset.

In [8]:
print(iris_dataset['data'].shape)

(150, 4)


# 7. Print the first 5 rows of the iris dataset.

In [9]:
print(iris_dataset['data'][:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


# 8. Print the type of the target variable of the Iris dataset.

In [10]:
print(type(iris_dataset['target']))

<class 'numpy.ndarray'>


# 9. Print the shape of the target variable of the iris dataset.

In [11]:
print(iris_dataset['target'].shape)

(150,)


# 10. Print the entire target variable values of the iris dataset.

In [12]:
print(iris_dataset['target'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# 11. Import NumPy with import numpy as np and use the numpy.unique() function to print the unique values of the target variable of Iris dataset.

In [13]:
import numpy as np

In [14]:
print(np.unique(iris_dataset['target']))

[0 1 2]


# 12. Split dataset into train and test datasets using from sklearn.model_selection import train_test_split.

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

# 13. Print the shape of train/test datasets and the train/test target variables.

In [16]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

X_train shape: (112, 4)
y_train shape: (112,)


# 14. Build your K-neighbors classifier for nearest neighbor of 1 using from sklearn.neighbors import KNeighborsClassifier, fit the model to your train dataset and make a prediction for the data point of [5, 1.9, 1, 0.2]. Print your prediction class value as an integer and also the corresponding string label.

In [18]:
#build k-neighbors classifier for nearest neighbor of 1
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [19]:
#fit model to train dataset
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [20]:
X_new = np.array([[5,1.9,1,0.2]])
print("X-new.shape:", X_new.shape)

X-new.shape: (1, 4)


In [21]:
prediction = knn.predict(X_new)
print("Prediction= ", prediction)

Prediction=  [0]


In [23]:
print("Predicted target name = "
     ,iris_dataset['target_names'][prediction])

Predicted target name =  ['setosa']


In [25]:
#evaluate the model on the test dataset, print the accuracy of the model
y_pred = knn.predict(X_test)
print("Test set predictions:\n", y_pred)

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [26]:
#print accuracy
print("Test set score: {:.2f}".format(np.mean(y_pred == y_test)))

Test set score: 0.97


In [27]:
print("Test set score: {:.2f}".format(knn.score(X_test, y_test)))

Test set score: 0.97


This model is 97% accurate.