1- Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [1]:
import numpy as np

In [2]:
sqmeters = [148, 160, 175, 190, 188, 220, 213, 202, 198, 209]
rooms = [3, 4, 2, 1, 3, 3, 2, 2, 4, 5]
price = [150000, 250000, 160000, 125000, 170000, 180000, 200000, 220000, 280000, 300000]

house_array = np.array((sqmeters, rooms, price))
print(house_array)

[[   148    160    175    190    188    220    213    202    198    209]
 [     3      4      2      1      3      3      2      2      4      5]
 [150000 250000 160000 125000 170000 180000 200000 220000 280000 300000]]


2- Transpose the array you have created, so that every line can represent features of one house.

In [3]:
house_features = house_array.transpose()
print(house_features)

[[   148      3 150000]
 [   160      4 250000]
 [   175      2 160000]
 [   190      1 125000]
 [   188      3 170000]
 [   220      3 180000]
 [   213      2 200000]
 [   202      2 220000]
 [   198      4 280000]
 [   209      5 300000]]


3- Display the shape of the array and explain what it means.

In [4]:
print(house_features.shape)

(10, 3)


.shape returns a tuple of (number of rows, number of columns) in the array. So, the house_features array has 10 rows and 3 columns.

4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [7]:
import os

In [8]:
os.getcwd()

'C:\\Users\\plw40'

In [16]:
os.chdir('C:\\Users\\plw40\\Downloads\\Datasets-20240611')

In [39]:
import csv

In [41]:
with open("C:\\Users\\plw40\\Downloads\\Datasets-20240611\\earthquakes1970-2014.csv", 'r') as f:
    reader = csv.reader(f)
    data = list(reader)

In [42]:
earthquakes = np.array(data)

5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [43]:
print(earthquakes.shape)

(5305, 12)


In [44]:
cols = [2,4,5,6,11] #index location is column number-1 bc index starts at 0
eq_slice = earthquakes[:20, cols]
display(eq_slice)


array([['Longitude', 'Magnitude', 'MagType', 'NbStations', 'EventID'],
       ['102.503000000000000', '7.50', 'Ms', '90', '1970010440'],
       ['151.458000000000000', '6.20', 'Ms', '85', '1970010640'],
       ['178.568000000000000', '6.10', 'Mb', '59', '1970010840'],
       ['126.736999999999000', '6.10', 'Mb', '91', '1970011040'],
       ['-152.660000000000000', '6.00', 'ML', '0', ''],
       ['-177.348999999999000', '6.50', 'Mb', '175', '1970012040'],
       ['142.966000000000000', '6.40', 'Ms', '199', '1970012040'],
       ['-104.298000000000000', '6.60', 'Ms', '140', '1970012140'],
       ['166.370000000000000', '6.40', 'Ms', '91', '1970012640'],
       ['-99.483999999999900', '6.50', 'Ms', '100', '1970020440'],
       ['122.117000000000000', '6.60', 'Ms', '94', '1970020540'],
       ['100.775000000000000', '6.10', 'Ms', '57', '1970020640'],
       ['103.031000000000000', '6.00', 'Ms', '94', '1970022440'],
       ['-179.589800000000000', '6.00', 'ML', '0', ''],
       ['-175.03999

In [45]:
print(eq_slice.shape) #check shape

(20, 5)


In [46]:
print(earthquakes[0,])

['DateTime' 'Latitude' 'Longitude' 'Depth' 'Magnitude' 'MagType'
 'NbStations' 'Gap' 'Distance' 'RMS' 'Source' 'EventID']


6- Display the row numbers where last? (magnitude?) values are equal to 4.5 or higher.